---
# Vault service
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
---
# Rabbitmq service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
# Redis service
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
# ---
# # Auth-service LoadBalancer Service
# apiVersion: v1
# kind: Service
# metadata:
#   name: auth
# spec:
#   type: LoadBalancer
#   selector:
#     app: auth
#   ports:
#     - name: auth-port
#       protocol: TCP
#       port: 3000
#       targetPort: 3000
# ---
# # Order-service LoadBalancer Service
# apiVersion: v1
# kind: Service
# metadata:
#   name: order
# spec:
#   type: LoadBalancer
#   selector:
#     app: order
#   ports:
#     - name: order-port
#       protocol: TCP
#       port: 3200
#       targetPort: 3200
# ---
# # Notification-service LoadBalancer Service
# apiVersion: v1
# kind: Service
# metadata:
#   name: notification
# spec:
#   type: LoadBalancer
#   selector:
#     app: notification
#   ports:
#     - name: notification-port
#       protocol: TCP
#       port: 3100
#       targetPort: 3100
# ---
# # User-service LoadBalancer Service
# apiVersion: v1
# kind: Service
# metadata:
#   name: user
# spec:
#   type: LoadBalancer
#   selector:
#     app: user
#   ports:
#     - name: user-port
#       protocol: TCP
#       port: 3300
#       targetPort: 3300